apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: waveforge-pro-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
spec:
  rules:
    - host: dev.waveforge-pro.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: waveforge-pro-service
                port:
                  number: 80
  tls:
    - hosts:
        - dev.waveforge-pro.example.com
      secretName: waveforge-pro-dev-tls
